### ISSUE TITLE
Query Fields of an Object

### ISSUE THREAD

**Issue by jomayan** [roblesterjr04/EloquentSalesForce#10]
How do I query all fields of an Object ?

**Comment by jayomayan** [comment]
Anyone?

**Comment by seankndy** [comment]
Jay -- read the documentation.  It's only returning a portion of the fields
because that's the default.  Look into the public $columns property.

**Comment by roblesterjr04** [comment]
Sorry for the delay here all, Yes, because SOQL does not offer a * query option, if you don't specify columns, I query the compact layout of the object and display those fields. If you want a specific set of columns/fields, you need to either set the `public $colums = []` array or use the normal `select()` method on the model.
